version: "2.4"
services:
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres-development
    image: postgres:9.6
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
